import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { poppins, montserrat } from "./fonts/fonts";
import ToasterConfig from "../utils/ToasterConfig";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/header/Navbar";

export const metadata: Metadata = {
  title: "Budget Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html data-theme="cupcake" lang="fr" suppressHydrationWarning>
        <body className={`${poppins.className} antialiased min-w-[300px]`}>
          <ToasterConfig />
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Navbar />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
